locals {
  location_slug = lookup(zipmap(values(local.regions), keys(local.regions)), var.azure_region, lookup(zipmap(values(local.cli_names), keys(local.cli_names)), var.azure_region, var.azure_region))

  # Azure region mapping between slug and standard format.

  regions = {
    eastus              = "East US"
    eastus2             = "East US 2"
    southcentralus      = "South Central US"
    westus2             = "West US 2"
    westus3             = "West US 3"
    australiaeast       = "Australia East"
    southeastasia       = "Southeast Asia"
    northeurope         = "North Europe"
    swedencentral       = "Sweden Central"
    uksouth             = "UK South"
    westeurope          = "West Europe"
    centralus           = "Central US"
    southafricanorth    = "South Africa North"
    centralindia        = "Central India"
    eastasia            = "East Asia"
    japaneast           = "Japan East"
    koreacentral        = "Korea Central"
    canadacentral       = "Canada Central"
    francecentral       = "France Central"
    germanywestcentral  = "Germany West Central"
    norwayeast          = "Norway East"
    polandcentral       = "Poland Central"
    switzerlandnorth    = "Switzerland North"
    uaenorth            = "UAE North"
    brazilsouth         = "Brazil South"
    centraluseuap       = "Central US EUAP"
    eastus2euap         = "East US 2 EUAP"
    qatarcentral        = "Qatar Central"
    centralusstage      = "Central US (Stage)"
    eastusstage         = "East US (Stage)"
    eastus2stage        = "East US 2 (Stage)"
    northcentralusstage = "North Central US (Stage)"
    southcentralusstage = "South Central US (Stage)"
    westusstage         = "West US (Stage)"
    westus2stage        = "West US 2 (Stage)"
    asia                = "Asia"
    asiapacific         = "Asia Pacific"
    australia           = "Australia"
    brazil              = "Brazil"
    canada              = "Canada"
    europe              = "Europe"
    france              = "France"
    germany             = "Germany"
    global              = "Global"
    india               = "India"
    japan               = "Japan"
    korea               = "Korea"
    norway              = "Norway"
    singapore           = "Singapore"
    southafrica         = "South Africa"
    switzerland         = "Switzerland"
    uae                 = "United Arab Emirates"
    uk                  = "United Kingdom"
    unitedstates        = "United States"
    unitedstateseuap    = "United States EUAP"
    eastasiastage       = "East Asia (Stage)"
    southeastasiastage  = "Southeast Asia (Stage)"
    brazilus            = "Brazil US"
    eastusstg           = "East US STG"
    northcentralus      = "North Central US"
    westus              = "West US"
    jioindiawest        = "Jio India West"
    westcentralus       = "West Central US"
    southafricawest     = "South Africa West"
    australiacentral    = "Australia Central"
    australiacentral2   = "Australia Central 2"
    australiasoutheast  = "Australia Southeast"
    japanwest           = "Japan West"
    jioindiacentral     = "Jio India Central"
    koreasouth          = "Korea South"
    southindia          = "South India"
    westindia           = "West India"
    canadaeast          = "Canada East"
    francesouth         = "France South"
    germanynorth        = "Germany North"
    norwaywest          = "Norway West"
    switzerlandwest     = "Switzerland West"
    ukwest              = "UK West"
    uaecentral          = "UAE Central"
    brazilsoutheast     = "Brazil Southeast"
    #Azure US Government
    usgovvirginia = "USGov Virginia" # US Government zones
    usgovtexas    = "USGov Texas"    # US Government zones
    usgovarizona  = "USGov Arizona"  # US Government zones
    usdodeast     = "USDoD East"     # US DoD zones
    usdodcentral  = "USDoD Central"  # US DoD zones


    # Global/continental zones
    "asia"        = "Asia"
    "asiapacific" = "Asia Pacific"
    "aus"         = "Australia"
    "bra"         = "Brazil"
    "can"         = "Canada"
    "eu"          = "Europe"
    "global"      = "Global"
    "ind"         = "India"
    "jap"         = "Japan"
    "uk"          = "United Kingdom"
    "us"          = "United States"
  }
  # Short names derived from ISO 3166-1 alpha-2 country codes
  short_names = {
    "eastus"              = "eus"
    "eastus2"             = "eus2"
    "southcentralus"      = "scus"
    "westus2"             = "wus2"
    "westus3"             = "wus3"
    "australiaeast"       = "aue"
    "southeastasia"       = "seas"
    "northeurope"         = "ne"
    "swedencentral"       = "sec"
    "uksouth"             = "uks"
    "westeurope"          = "we"
    "centralus"           = "cus"
    "southafricanorth"    = "zan"
    "centralindia"        = "cin"
    "eastasia"            = "eas"
    "japaneast"           = "jpe"
    "koreacentral"        = "krc"
    "canadacentral"       = "cac"
    "francecentral"       = "frc"
    "germanywestcentral"  = "dewc"
    "norwayeast"          = "noe"
    "polandcentral"       = "plc"
    "switzerlandnorth"    = "chn"
    "uaenorth"            = "aen"
    "brazilsouth"         = "brs"
    "centraluseuap"       = "cuseuap"
    "eastus2euap"         = "eus2euap"
    "qatarcentral"        = "qac"
    "centralusstage"      = "cuss"
    "eastusstage"         = "euss"
    "eastus2stage"        = "eus2s"
    "northcentralusstage" = "ncuss"
    "southcentralusstage" = "scuss"
    "westusstage"         = "wuss"
    "westus2stage"        = "wus2s"
    "asia"                = "as"
    "asiapacific"         = "ap"
    "australia"           = "au"
    "brazil"              = "br"
    "canada"              = "ca"
    "europe"              = "eu"
    "france"              = "fr"
    "germany"             = "dewc"
    "global"              = "g"
    "india"               = "in"
    "japan"               = "jp"
    "korea"               = "kr"
    "norway"              = "no"
    "singapore"           = "sg"
    "southafrica"         = "za"
    "switzerland"         = "ch"
    "unitedstates"        = "us"
    "uk"                  = "uk"
    "unitedstateseuap"    = "useuap"
    "eastasiastage"       = "eas"
    "southeastasiastage"  = "seass"
    "brazilus"            = "brus"
    "northcentralus"      = "ncus"
    "westus"              = "wus"
    "jioindiawest"        = "jinw"
    "centraluseuap"       = "cuseuap"
    "westcentralus"       = "wcus"
    "southafricawest"     = "zaw"
    "australiacentral"    = "auc"
    "australiacentral2"   = "auc2"
    "australiasoutheast"  = "ause"
    "japanwest"           = "jpw"
    "jioindiacentral"     = "jinc"
    "koreasouth"          = "krs"
    "southindia"          = "sin"
    "westindia"           = "win"
    "canadaeast"          = "cae"
    "francesouth"         = "frs"
    "germanynorth"        = "den"
    "norwaywest"          = "now"
    "switzerlandwest"     = "chw"
    "ukwest"              = "ukw"
    "uaecentral"          = "aec"
    "brazilsoutheast"     = "brse"


    # US Government zones
    "usgovvirginia" = "usgva"
    "usgovtexas"    = "usgtx"
    "usgovarizona"  = "usgaz"
    "usdodeast"     = "usde"
    "usdodcentral"  = "usdc"

    # Global/continental zones
    "asia"        = "asia"   # Asia
    "asiapacific" = "asiapa" # Asia Pacific
    "aus"         = "aus"    # Australia
    "bra"         = "bra"    # Brazil
    "can"         = "can"    # Canada
    "eu"          = "eu"     # Europe
    "global"      = "glob"   # Global
    "ind"         = "ind"    # India
    "jap"         = "jap"    # Japan
    "uk"          = "uk"     # United Kingdom
    "us"          = "us"     # United States
  }

  # Thoses region CLI name where partially generated via
  # `az account list-locations --output json | jq -r '.[] | "\"\" = \"" + .name + "\" # " + .displayName'`
  cli_names = {
    "eastus"              = "eastus"              # East US
    "eastus2"             = "eastus2"             # East US 2
    "southcentralus"      = "southcentralus"      # South Central US
    "westus2"             = "westus2"             # West US 2
    "westus3"             = "westus3"             # West US 3
    "australiaeast"       = "australiaeast"       # Australia East
    "southeastasia"       = "southeastasia"       # Southeast Asia
    "northeurope"         = "northeurope"         # North Europe
    "swedencentral"       = "swedencentral"       # Sweden Central
    "uksouth"             = "uksouth"             # UK South
    "westeurope"          = "westeurope"          # West Europe
    "centralus"           = "centralus"           # Central US
    "southafricanorth"    = "southafricanorth"    # South Africa North
    "centralindia"        = "centralindia"        # Central India
    "eastasia"            = "eastasia"            # East Asia
    "japaneast"           = "japaneast"           # Japan East
    "koreacentral"        = "koreacentral"        # Korea Central
    "canadacentral"       = "canadacentral"       # Canada Central
    "francecentral"       = "francecentral"       # France Central
    "germanywestcentral"  = "germanywestcentral"  # Germany West Central
    "norwayeast"          = "norwayeast"          # Norway East
    "polandcentral"       = "polandcentral"       # Poland Central
    "switzerlandnorth"    = "switzerlandnorth"    # Switzerland North
    "uaenorth"            = "uaenorth"            # UAE North
    "brazilsouth"         = "brazilsouth"         # Brazil South
    "centraluseuap"       = "centraluseuap"       # Central US EUAP
    "eastus2euap"         = "eastus2euap"         # East US 2 EUAP
    "qatarcentral"        = "qatarcentral"        # Qatar Central
    "centralusstage"      = "centralusstage"      # Central US (Stage)
    "eastusstage"         = "eastusstage"         # East US (Stage)
    "eastus2stage"        = "eastus2stage"        # East US 2 (Stage)
    "northcentralusstage" = "northcentralusstage" # North Central US (Stage)
    "southcentralusstage" = "southcentralusstage" # South Central US (Stage)
    "westusstage"         = "westusstage"         # West US (Stage)
    "westus2stage"        = "westus2stage"        # West US 2 (Stage)
    "asia"                = "asia"                # Asia
    "asiapacific"         = "asiapacific"         # Asia Pacific
    "australia"           = "australia"           # Australia
    "brazil"              = "brazil"              # Brazil
    "canada"              = "canada"              # Canada
    "europe"              = "europe"              # Europe
    "france"              = "france"              # France
    "germany"             = "germany"             # Germany
    "global"              = "global"              # Global
    "india"               = "india"               # India
    "japan"               = "japan"               # Japan
    "korea"               = "korea"               # Korea
    "norway"              = "norway"              # Norway
    "singapore"           = "singapore"           # Singapore
    "southafrica"         = "southafrica"         # South Africa
    "switzerland"         = "switzerland"         # Switzerland
    "uae"                 = "uae"                 # United Arab Emirates
    "uk"                  = "uk"                  # United Kingdom
    "unitedstates"        = "unitedstates"        # United States
    "unitedstateseuap"    = "unitedstateseuap"    # United States EUAP
    "eastasiastage"       = "eastasiastage"       # East Asia (Stage)
    "southeastasiastage"  = "southeastasiastage"  # Southeast Asia (Stage)
    "brazilus"            = "brazilus"            # Brazil US
    "eastusstg"           = "eastusstg"           # East US STG
    "northcentralus"      = "northcentralus"      # North Central US
    "westus"              = "westus"              # West US
    "jioindiawest"        = "jioindiawest"        # Jio India West
    "westcentralus"       = "westcentralus"       # West Central US
    "southafricawest"     = "southafricawest"     # South Africa West
    "australiacentral"    = "australiacentral"    # Australia Central
    "australiacentral2"   = "australiacentral2"   # Australia Central 2
    "australiasoutheast"  = "australiasoutheast"  # Australia Southeast
    "japanwest"           = "japanwest"           # Japan West
    "jioindiacentral"     = "jioindiacentral"     # Jio India Central
    "koreasouth"          = "koreasouth"          # Korea South
    "southindia"          = "southindia"          # South India
    "westindia"           = "westindia"           # West India
    "canadaeast"          = "canadaeast"          # Canada East
    "francesouth"         = "francesouth"         # France South
    "germanynorth"        = "germanynorth"        # Germany North
    "norwaywest"          = "norwaywest"          # Norway West
    "switzerlandwest"     = "switzerlandwest"     # Switzerland West
    "ukwest"              = "ukwest"              # UK West
    "uaecentral"          = "uaecentral"          # UAE Central
    "brazilsoutheast"     = "brazilsoutheast"     # Brazil Southeast

    "usgovvirginia" = "usgovvirginia" # "US Gov Virginia"
    "usgovtexas"    = "usgovtexas"    # "US Gov Texas"
    "usgovarizona"  = "usgovarizona"  # "US Gov Arizona"
    "usdodeast"     = "usdodeast"     # "US DoD East"
    "usdodcentral"  = "usdodcentral"  # "US DoD Central"
  }

  # Based on https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure
  # Can be retrieved by cli too:
  # `az account list-locations -o table --query '[].[displayName, name, metadata.pairedRegion[0].name]'`
  paired = {
    eastus             = "westus"
    eastus2            = "centralus"
    southcentralus     = "northcentralus"
    westus2            = "westcentralus"
    westus3            = "eastus"
    australiaeast      = "australiasoutheast"
    southeastasia      = "eastasia"
    northeurope        = "westeurope"
    swedencentral      = "swedensouth"
    uksouth            = "ukwest"
    westeurope         = "northeurope"
    centralus          = "eastus2"
    southafricanorth   = "southafricawest"
    centralindia       = "southindia"
    eastasia           = "southeastasia"
    japaneast          = "japanwest"
    koreacentral       = "koreasouth"
    canadacentral      = "canadaeast"
    francecentral      = "francesouth"
    germanywestcentral = "germanynorth"
    norwayeast         = "norwaywest"
    polandcentral      = ""
    switzerlandnorth   = "switzerlandwest"
    uaenorth           = "uaecentral"
    brazilsouth        = "southcentralus"
    centraluseuap      = "eastus2euap"
    eastus2euap        = "centraluseuap"
    brazilus           = "Brazil Southeast"
    eastusstg          = "southcentralusstg"
    northcentralus     = "southcentralus"
    westus             = "eastus"
    jioindiawest       = "jioindiacentral"
    westcentralus      = "westus2"
    southafricawest    = "southafricanorth"
    australiacentral   = "australiacentral"
    australiacentral2  = "australiacentral2"
    australiasoutheast = "australiaeast"
    japanwest          = "japaneast"
    jioindiacentral    = "jioindiawest"
    koreasouth         = "koreacentral"
    southindia         = "centralindia"
    westindia          = "southindia"
    canadaeast         = "canadacentral"
    francesouth        = "francecentral"
    germanynorth       = "germanywestcentral"
    norwaywest         = "norwayeast"
    switzerlandwest    = "switzerlandnorth"
    ukwest             = "uksouth"
    uaecentral         = "uaenorth"
    brazilsoutheast    = "brazilsouth"
    #Azure US Gov Regions
    usgovvirginia = "usgovtexas"
    usgovarizona  = "usgovtexas"
    usdodcentral  = "usdodeast"
    usdodeast     = "usdodcentral"
    usgovtexas    = "usgovarizona"
  }

  paired_region = try(local.paired[local.location_slug], null)
}
